"""The runtime's native reactive graph (rust/vm/src/core.rs); `frontage.reactive` wraps it."""

from collections.abc import Callable
from typing import Any

UNSET: Any
CLEAN: int
CHECK: int
DIRTY: int

class Owner:
    name: Any
    _parent: Any
    _context: Any
    _disposed: bool
    _owned: list[Any]
    _cleanups: list[Any]
    def __init__(self, parent: Any = ...) -> None: ...
    def dispose(self) -> None: ...
    def on_cleanup(self, fn: Callable[[], Any]) -> Callable[[], Any]: ...
    def run(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...
    def __enter__(self) -> Owner: ...
    def __exit__(self, *exc: Any) -> bool: ...

class Signal:
    _value: Any
    _observers: list[Any]
    def __init__(self, value: Any, equal: Callable[[Any, Any], bool] | None = None) -> None: ...
    def __call__(self) -> Any: ...
    @property
    def value(self) -> Any: ...
    def peek(self) -> Any: ...
    def set(self, value: Any) -> bool: ...
    def _write(self, value: Any) -> bool: ...
    def update(self, fn: Callable[[Any], Any]) -> bool: ...

class Memo(Owner):
    _value: Any
    _fn: Any
    _loading: Any
    _error: Any
    _scopes: list[Any]
    def __init__(self, fn: Callable[[], Any], equal: Callable[[Any, Any], bool] | None = None) -> None: ...
    def __call__(self) -> Any: ...
    @property
    def value(self) -> Any: ...
    def peek(self) -> Any: ...
    def loading(self) -> bool: ...
    def error(self) -> Any: ...
    def is_async(self) -> bool: ...

class Effect(Owner):
    _fn: Any
    _state: int
    _queued: bool
    _render: bool
    _urgent: bool
    def __init__(self, compute: Callable[[], Any], effect: Callable[[Any, Any], Any] | None = None, target: Callable[[], bool] | None = None) -> None: ...
    def _commit_parked(self) -> None: ...

class RenderEffect(Effect): ...

def get_owner() -> Any: ...
def listener() -> Any: ...
def set_scope(owner: Any, listener: Any) -> None: ...
def run_with_owner(owner: Any, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...
def on_cleanup(fn: Callable[[], Any]) -> Callable[[], Any]: ...
def untrack(fn: Callable[..., Any], *args: Any) -> Any: ...
def begin_batch() -> None: ...
def end_batch() -> None: ...
def batch_depth() -> int: ...
def flushing() -> bool: ...
def untracking() -> int: ...
def lookup(owner: Any, ctx: Any) -> Any: ...
def route_error(owner: Any, exc: BaseException) -> None: ...
def mark(node: Any, state: int) -> None: ...
def queue_render(effect: Any) -> None: ...
def transition() -> Any: ...
def set_transition(t: Any) -> None: ...
def set_debug(flag: bool) -> None: ...
def async_task(delta: int) -> None: ...
def is_node(x: Any) -> bool: ...
def setup(**hooks: Any) -> None: ...
