"""The runtime's DOM op stream (rust/vm/src/dom.rs); `frontage.dom.StreamRenderer` is written over it."""

from typing import Any

available: bool

def define_template(html: str) -> int: ...
def clone(tid: int) -> int: ...
def find_holes(root: int, n_elements: int, n_markers: int, keep: bool) -> int: ...
def create_element(tag: str) -> int: ...
def create_text(text: str) -> int: ...
def create_comment(text: str) -> int: ...
def set_text(node: int, text: str) -> None: ...
def set_attr(node: int, name: str, value: str) -> None: ...
def remove_attr(node: int, name: str) -> None: ...
def set_prop(node: int, name: str, value: str) -> None: ...
def set_prop_bool(node: int, name: str, on: bool) -> None: ...
def toggle_class(node: int, name: str, on: bool) -> None: ...
def set_style(node: int, prop: str, value: str) -> None: ...
def remove_style(node: int, prop: str) -> None: ...
def append(parent: int, node: int) -> None: ...
def insert(parent: int, node: int, anchor: int) -> None: ...
def remove(parent: int, node: int) -> None: ...
def replace(parent: int, new: int, old: int) -> None: ...
def listen(node: int, event: str) -> None: ...
def unlisten(node: int, event: str) -> None: ...
def release(node: int) -> None: ...
def set_dispatcher(fn: Any) -> None: ...
def teardown() -> None: ...
def flush() -> None: ...
def query(kind: int, node: int) -> int: ...
def node(node: int) -> Any: ...
def id_of(node: Any) -> int: ...
