"""The runtime's own module (rust/vm/src/modules.rs): the collector, the profiler, the clock,
and what the dev swap needs."""

from typing import Any

browser: bool

def collect() -> int: ...
def heap_len() -> int: ...
def format_exception(exc: BaseException) -> str: ...
def sleep_ms(ms: float) -> None: ...
def monotonic() -> float: ...
def profile_start() -> None: ...
def profile_stop() -> list[tuple[str, str, int, float, float]]: ...
def run_module_as_main(name: str) -> None: ...
