"""CPython only: the `frontage-schema` command. Pydantic models in, a schemas module out.

    frontage-schema app.models:User app.models:Order -o app/schemas.py

Each model is imported, asked for `model_json_schema()`, read by `from_json_schema` and
written as the source `repr` prints — so the page gets a plain frontage schema, and Pydantic
never leaves CPython (it cannot run in the page: MicroPython keeps no `__annotations__`).
Anything that only exists as Python — a `@field_validator`, a `@model_validator` — does not
cross, and the generated file names each one it skipped.

`--json FILE` reads a JSON Schema document instead of a model, for an API whose schema is
published (an OpenAPI document under `--ref '#/components/schemas/User'`).

The leading underscore is what keeps it out of the page: `frontage build` packs a component's
modules except the private ones, and this one would only be 4 KB of dead weight there.
"""

__all__ = ["compile_json", "compile_models", "main"]


def compile_models(specs):
    """Source for `NAME = <schema>` lines, one per `module:Model` spec."""
    import importlib

    from .jsonschema import from_json_schema

    lines = [
        "# Generated by `frontage-schema` from Pydantic models; edit the models, not this file.",
        "from frontage_schema import *  # noqa: F403",
        "",
    ]
    for spec in specs:
        module_name, _, attr = spec.partition(":")
        if not attr:
            raise SystemExit("expected module:Model, got " + repr(spec))
        model = getattr(importlib.import_module(module_name), attr)
        document = model.model_json_schema()
        skipped = _validators(model)
        for note in skipped:
            lines.append("# " + attr + ": " + note + " is Python on the server and did not cross")
        lines.append(attr + " = " + repr(from_json_schema(document)))
        lines.append("")
    return "\n".join(lines)


def compile_json(path, ref=None):
    import json

    from .jsonschema import _resolve, from_json_schema

    with open(path) as f:
        document = json.load(f)
    node = _resolve(ref, document) if ref else document
    name = node.get("title") or (ref.rsplit("/", 1)[-1] if ref else "Schema")
    return "\n".join(
        [
            "# Generated by `frontage-schema` from " + path + "; edit the document, not this file.",
            "from frontage_schema import *  # noqa: F403",
            "",
            _identifier(name) + " = " + repr(from_json_schema(node, document)),
            "",
        ]
    )


def _validators(model):
    decorators = getattr(model, "__pydantic_decorators__", None)
    if decorators is None:
        return []
    out = []
    for kind in ("field_validators", "model_validators"):
        for name in getattr(decorators, kind, {}) or {}:
            out.append(kind.replace("_", " ")[:-1] + " " + name)
    return out


def _identifier(name):
    out = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    return out if out and not out[0].isdigit() else "Schema_" + out


def main(argv=None):
    import argparse
    import sys

    parser = argparse.ArgumentParser(
        prog="frontage-schema", description="Pydantic models or a JSON Schema in, a frontage schemas module out."
    )
    parser.add_argument("specs", nargs="*", help="module:Model, importable from the current directory")
    parser.add_argument("--json", metavar="FILE", help="read a JSON Schema document instead")
    parser.add_argument(
        "--ref", metavar="POINTER", help="with --json: the node to compile, e.g. '#/components/schemas/User'"
    )
    parser.add_argument("-o", "--output", metavar="FILE", help="write here instead of stdout")
    args = parser.parse_args(argv)
    if bool(args.specs) == bool(args.json):
        parser.error("give module:Model specs, or --json FILE")
    sys.path.insert(0, "")
    source = compile_json(args.json, args.ref) if args.json else compile_models(args.specs)
    if args.output:
        with open(args.output, "w") as f:
            f.write(source)
        print("wrote " + args.output)
    else:
        sys.stdout.write(source)
    return 0
