s = "Hello, World"
print(s.lower(), s.upper(), s.title(), s.swapcase(), "hello world".capitalize(), s.casefold())
print(s.find("o"), s.rfind("o"), s.find("z"), s.index("W"), s.count("l"), s.count(""), s.startswith("He"), s.endswith(("x", "ld")), s.startswith(("a", "H")))
print(s.replace("l", "L"), s.replace("l", "L", 1), s.split(", "), s.split(), "a,b,,c".split(","), "a b  c ".split(), "a,b,c".split(",", 1), "a,b,c".rsplit(",", 1))
print("  pad  ".strip(), "  pad  ".lstrip(), "  pad  ".rstrip(), "xxhixx".strip("x"), "xxhixx".lstrip("x"), "--a--".rstrip("-"))
print(", ".join(["a", "b", "c"]), "".join("xyz"), "-".join(str(i) for i in range(4)), "a" + "b", "ab" * 3, 3 * "ab")
print("abc"[0], "abc"[-1], "abcdef"[1:4], "abcdef"[::2], "abcdef"[::-1], "abcdef"[-3:], "abcdef"[:-2], "abcdef"[10:], "abc"[1:1])
print("a" in "abc", "d" not in "abc", "" in "abc", len(""), len("abc"), "abc" == "abc", "abc" < "abd", "abc" != "abc")
print("42".isdigit(), "4a".isdigit(), "abc".isalpha(), "ab1".isalnum(), "  ".isspace(), "ABC".isupper(), "abc".islower(), "Abc".isupper(), "x_1".isidentifier(), "1x".isidentifier())
print("a-b".partition("-"), "a-b-c".rpartition("-"), "abc".partition("-"), "l1\nl2\r\nl3".splitlines(), "l1\nl2\n".splitlines(True))
print("42".zfill(5), "-42".zfill(5), "ab".center(6, "*"), "ab".ljust(5, "."), "ab".rjust(5), "ab".center(7))
print("prefix_x".removeprefix("prefix_"), "x_suffix".removesuffix("_suffix"), "a\tb".expandtabs(4), "hello".encode(), b"bytes".decode())
print("{} {}".format(1, 2), "{1} {0}".format("a", "b"), "{x} {y}".format(x=1, y=2), "{:>5}|{:<5}|{:^5}|".format("a", "b", "c"), "{:05d} {:.3f} {:,} {:x} {:b} {:e}".format(42, 3.14159, 1234567, 255, 5, 12345.678))
print("{0[0]} {0[1]}".format([1, 2]), "{a.real}".format(a=1) if False else "skip", "{!r} {!s}".format("q", "q"), "{{}} {}".format(1), "{:%}".format(0.25), "{:.1%}".format(0.256))
print(f"{1+1}", f"{'nested'}", f"{3.14159:.2f}", f"{42:>6}", f"{'x':*^7}", f"{255:#x}", f"{1234567:,}", f"{0.5:.0%}", f"{'a'!r}", f"{[1, 2]}", f"{{literal}}")
w = 10; p = 3; v = 3.14159
print(f"{v:{w}.{p}f}|", f"{v:>{w}}|", f"{v=}", f"{v = }", f"{v=:.1f}", f"{w!r:>4}")
print("%d %s %r %5.1f %-4d| %03d %x %o %e %c %%" % (1, "s", "r", 3.14159, 7, 5, 255, 8, 1234.5, 65), "%s" % "one", "%(a)s %(b)d" % {"a": "x", "b": 2}, "%.3s" % "abcdef", "%5s|%-5s|" % ("a", "b"))
print(str(b"abc"), repr(b"a\nb"), b"abc"[0], b"abc"[1:], len(b"abc"), bytes([65, 66]), bytes(3), b"ab" + b"cd", b"a" * 3, bytearray(b"xy"), list(b"ab"))
print("Straße".upper(), "ǅ".lower(), "ß".casefold() if False else "", "café".upper(), "İ".lower() == "i̇", "abc".translate if False else "")
print(ascii("héllo"), ascii("日本"), "日本".encode("utf-8"), "%s" % "日本", f"{'日本':>4}|", "日本語"[1:], "日本語".find("語"), "日本語".index("本"))
print(sorted("banana"), sorted(["b", "A", "c"]), sorted(["b", "A", "c"], key=str.lower), "a".join(sorted(set("banana"))))
print(str(1e100), str(1.5e300 * 1e10), repr(1e-300 / 1e10), 1.0 // 0.3, 2.5 % 1, -2.5 % 1, 1e300 * 10 == float("inf"))
