"""Frontage: a fine-grained reactive UI framework for Python in the browser.

M5 of the rewrite (see DESIGN.md): the reactive core, the store, reactive views with the
insert rules, templates (`h` and `html(t"…")`), control flow and boundaries, Resource and
Action, the router, widgets, State, delegated events, and the DOM renderer.
"""

from .aio import Action, Resource, interval, poll
from .errors import FrontageError, NotReady, RenderError, format_exception
from .flow import Dynamic, Errored, For, Loading, Match, Portal, Show, Switch
from .reactive import (
    Context,
    Effect,
    Memo,
    Optimistic,
    Owner,
    RenderEffect,
    Signal,
    Transition,
    batch,
    get_owner,
    is_pending,
    on,
    on_cleanup,
    on_mount,
    provide,
    run_with_owner,
    selector,
    spawn,
    transition,
    tree,
    untrack,
    use,
    use_transition,
)
from .renderer import HtmlRenderer, RecordingRenderer, Renderer
from .router import A, ActionForm, Navigate, Redirect, Route, Router, use_location, use_navigate, use_params, use_query
from .runtime import in_browser, platform
from .state import State, computed, field
from .store import Store, reconcile, snapshot
from .template import html
from .version import __version__
from .view import Element, Mounted, NodeRef, Text, build, component, emit, h, mount, render_to_string, text, unique_id

__all__ = [
    "tree",
    "unique_id",
    "A",
    "Action",
    "ActionForm",
    "Context",
    "Dynamic",
    "Effect",
    "Element",
    "Errored",
    "For",
    "FrontageError",
    "HtmlRenderer",
    "Loading",
    "Match",
    "Memo",
    "Mounted",
    "Navigate",
    "NodeRef",
    "NotReady",
    "Owner",
    "Portal",
    "RecordingRenderer",
    "Redirect",
    "RenderEffect",
    "RenderError",
    "Renderer",
    "Resource",
    "Route",
    "Router",
    "Show",
    "Signal",
    "State",
    "Store",
    "Switch",
    "Text",
    "Transition",
    "Optimistic",
    "is_pending",
    "transition",
    "use_transition",
    "__version__",
    "batch",
    "build",
    "component",
    "computed",
    "emit",
    "field",
    "format_exception",
    "get_owner",
    "h",
    "html",
    "in_browser",
    "interval",
    "mount",
    "on",
    "on_cleanup",
    "on_mount",
    "platform",
    "poll",
    "provide",
    "reconcile",
    "render_to_string",
    "run_with_owner",
    "selector",
    "snapshot",
    "spawn",
    "text",
    "untrack",
    "use",
    "use_location",
    "use_navigate",
    "use_params",
    "use_query",
]
