# The public names of `frontage`, and the module each lives in. One table, two readers:
# `frontage/__init__.py` resolves `from frontage import Signal` through it on first use
# (PEP 562, so a page loads only the modules it reaches), and `frontage build`'s import
# walk attributes the same name to the same module without importing anything. Keep it
# sorted by module, then name; `__init__.pyi` is generated from it by `mk exports`.

EXPORTS = {
    "Action": "aio",
    "Resource": "aio",
    "interval": "aio",
    "poll": "aio",
    "FrontageError": "errors",
    "NotReady": "errors",
    "RenderError": "errors",
    "format_exception": "errors",
    "Dynamic": "flow",
    "Errored": "flow",
    "For": "flow",
    "Loading": "flow",
    "Match": "flow",
    "Portal": "flow",
    "Show": "flow",
    "Switch": "flow",
    "Context": "reactive",
    "Effect": "reactive",
    "Memo": "reactive",
    "Optimistic": "reactive",
    "Owner": "reactive",
    "RenderEffect": "reactive",
    "Signal": "reactive",
    "Transition": "reactive",
    "batch": "reactive",
    "get_owner": "reactive",
    "is_pending": "reactive",
    "on": "reactive",
    "on_cleanup": "reactive",
    "on_mount": "reactive",
    "provide": "reactive",
    "run_with_owner": "reactive",
    "selector": "reactive",
    "spawn": "reactive",
    "transition": "reactive",
    "tree": "reactive",
    "untrack": "reactive",
    "use": "reactive",
    "use_transition": "reactive",
    "HtmlRenderer": "renderer",
    "RecordingRenderer": "renderer",
    "Renderer": "renderer",
    "A": "router",
    "ActionForm": "router",
    "Navigate": "router",
    "Redirect": "router",
    "Route": "router",
    "Router": "router",
    "use_location": "router",
    "use_navigate": "router",
    "use_params": "router",
    "use_query": "router",
    "in_browser": "runtime",
    "platform": "runtime",
    "State": "state",
    "computed": "state",
    "field": "state",
    "Store": "store",
    "reconcile": "store",
    "snapshot": "store",
    "html": "template",
    "Element": "view",
    "Mounted": "view",
    "NodeRef": "view",
    "Text": "view",
    "build": "view",
    "component": "view",
    "emit": "view",
    "h": "view",
    "mount": "view",
    "render_to_string": "view",
    "text": "view",
    "unique_id": "view",
}
