# Type stub: at runtime `field(0)` is a descriptor-like marker that `State.__getattribute__`
# resolves to the signal's value; for a checker the attribute *is* the value, and a computed
# is its result. The stub says so, so `self.count += 1` types as int arithmetic.
from typing import Any, Callable, TypeVar, overload

T = TypeVar("T")

@overload
def field(default: T, *, equal: Callable[[T, T], bool] | None = ...) -> T: ...
@overload
def field(*, default_factory: Callable[[], T], equal: Callable[[T, T], bool] | None = ...) -> T: ...
@overload
def field() -> Any: ...
def computed(fn: Callable[[Any], T]) -> T: ...

class State:
    def __init__(self, **values: Any) -> None: ...
    def signal(self, name: str) -> Any: ...
    def memo(self, name: str) -> Any: ...
    def snapshot(self) -> dict[str, Any]: ...

__all__ = ["State", "computed", "field"]
